### ISSUE TITLE
NPM start - Error: ENOENT: no such file or directory ./typings/main.d.ts

### ISSUE THREAD

**Issue by karlfloersch** [ngrx/angular2-store-example#23]
I was following the *Quick Start* guide and when I ran `npm install` I got this error message (right before it printed the dependency tree):

```
Done. Phantomjs binary available at /Users/kfloersch/workspace/eth/angular2-store-example/node_modules/phantomjs/lib/phantom/bin/phantomjs

> angular2-store-example@0.0.1 postinstall /Users/kfloersch/workspace/eth/angular2-store-example
> typings install && node setup-json-db.js

typings ERR! message Unable to read typings for "es6-promise". You need to make sure the main path is correct
typings ERR! caused by SyntaxError: Unexpected end of input

typings ERR! cwd /Users/kfloersch/workspace/eth/angular2-store-example
typings ERR! system Darwin 14.5.0
typings ERR! command "/usr/local/Cellar/node/5.5.0/bin/node" "/Users/kfloersch/workspace/eth/angular2-store-example/node_modules/typings/dist/bin/typings-install.js"
typings ERR! node -v v5.5.0
typings ERR! typings -v 0.4.1

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

angular2-store-example@0.0.1 /Users/kfloersch/workspace/eth/angular2-store-example
├── @ngrx/store@1.2.1
├
```

When I tried running `npm start` I got:
```

...more above...
ERROR in ./src/main.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/kfloersch/workspace/eth/angular2-store-example/typings/main.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at /Users/kfloersch/workspace/eth/angular2-store-example/node_modules/ts-loader/index.js:193:22
    at Array.forEach (native)
    at ensureTypeScriptInstance (/Users/kfloersch/workspace/eth/angular2-store-example/node_modules/ts-loader/index.js:190:17)
    at Object.loader (/Users/kfloersch/workspace/eth/angular2-store-example/node_modules/ts-loader/index.js:375:14)

ERROR in ./src/vendor.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/Users/kfloersch/workspace/eth/angular2-store-example/node_modules/ts-loader/index.js:410:33)
webpack: bundle is now VALID.
```

I tried installing `tsd` `typescript` `webpack` and a few others but it didn't help. I'm not really sure where to take it from here.  Thanks!

**Update 1: I didn't see the "you should install all these globals" in the README. I'll try that now and report on if it solves it**

**Update 2: I installed all those globals, and I performed `typings install` before `npm start` but no luck. Typings install complained about not finding a typing for `jasmine` and after installing `jasmine` globally, it started complaining about not having a typing for `angular-protractor`**

**Comment by timkindberg** [comment]
I think I had the same problem. I have seemed to get passed it by making sure to "install all of those globals" and then I did "typings search protractor --ambient" and it found an angular-protractor typing, so then I did "typings install angular-protractor --ambient" and said "Y" to "are you sure?" and it changed my typescript typings path to a valid one. Now when I do npm start my site finally shows up.

**Comment by karlfloersch** [comment]
@timkindberg, thanks for the tip! I had [this](https://github.com/npm/npm/issues/11015) issue with NPM a few days ago, which might have been contributing (or causing) the problem. I reinstalled Node and NPM which seems to have fixed the issue. 

When `npm install`ing this store example, I still get a few errors, but now when I run `npm start` everything starts up and runs as expected. Thanks again!
