### ISSUE TITLE
ChangeDetectionStrategy

### ISSUE THREAD

**Issue by cschroeter** [ngrx/angular2-store-example#24]
I may be wrong but isn't the ChangeDetectionStrategy inherited?
So you could get rid off of some changeDetection: ChangeDetectionStrategy.OnPush properties

**Comment by MarkPieszak** [comment]
ChangeDetectionStrategy is *not* inherited, that would/could cause huge problems (imagine if you were using 3rd party Components, etc).

**Comment by cschroeter** [comment]
It is. Please read / watch Pascal Precht's talk about change detection
https://www.youtube.com/watch?v=CUxD91DWkGM

**Comment by MarkPieszak** [comment]
Oh it *is* inherited then? I'll have to try this out later, that might be a mistake if so! Could have been consequences.

**Comment by cschroeter** [comment]
Eventually it might be a good idea to ad the changeDetection strategy on top of the component to be more explicit =)
